### PR TITLE
Alias resolve patch issue #51

### PR DESCRIPTION
**Pull request by SSoulaimane**
merge test utils pr #42 first

### CODE REVIEW

**Comment by SSoulaimane** [comment]
ref issue #51

**Comment by BBasile** [comment]
What did happen with all your PRs ? I didn't follow the project for a while and now i see that they are still not handled. I suppose there was no conflicts at the beginning. You should rebase them. Except the first one (that i reviewed, remember the "first indirection" problem) the others seem reasonable.

**Comment by BBasile** [comment]
Can you rebase please ? the conflict is just about the unittest

**Comment by BBasile** [comment]
You need to tweak ModuleCache so that it can work with the new RCIAllocator.
I suggest to change the type according to the the version has found in std.compiler.

**Pull request merged**
