### PR TITLE
dsymbol.modulecache: Scan added imports on-demand

### PR DESCRIPTION
**Pull request by CyberShadow**
Avoid the up-front cost of scanning potentially arbitrarily large directory trees (which may include network filesystems and other things best not touched).

Probably fixes https://github.com/dlang-community/DCD/issues/316.

### CODE REVIEW

**Comment by BBasile** [comment]
This looks good and even interesting at a personal title (IDE will start faster) but i want to test beforehand.

**Comment by CyberShadow** [comment]
@BBasile How do I reproduce that? Please add a test case for your fix.

**Comment by BBasile** [comment]
I don't think I can add a test for this but it's not too hard to to use your branch in DCD, assuming you build with make: just go to dsymbol submodule, add your fork as remote and create and checkout the right branch. Then to reproduce just type `import std.getopt:` and invoke completion(right after the colon) .Phobos sources must be in the DCD imports.

The crash might be due to the fact that completion is asked while the import statement is not finished.

**Comment by BBasile** [comment]
Wait, in dsymbol the test is not possible but maybe in DCD. Would this help ?

**Comment by CyberShadow** [comment]
Thanks, I reproduced it.

Yes, putting the test in DCD would be good. I made sure this passed the DCD test suite before submitting.

**Comment by CyberShadow** [comment]
Probably, it would be better to reduce std.getopt to the minimal code needed to reproduce the bug.

I can do this, since it looks I'm going to work on this anyway.

**Comment by CyberShadow** [comment]
>  I think you'll have to work on this if you want your lazy import being merged because for now this PR cannot be accepted.

Done: https://github.com/dlang-community/dsymbol/pull/117

The crash was when the return value (a DSymbol interior linked list) was empty (so the head DSymbol* was null). However, it shouldn't have been empty in this PR too, so I need to look at that again. But you can still merge the other PRs first.

**Pull request merged**
