### PR TITLE
add support for auto bools

### PR DESCRIPTION
**Pull request by BBasile**
Needed for https://github.com/dlang-community/DCD/issues/400. Already tested locally in DCD.

### CODE REVIEW

**Comment by BBasile** [comment]
@wilzbach about Appveyor, there's still something that's not properly set: https://ci.appveyor.com/project/greenify/dsymbol/build/1.0.31

**Comment by wilzbach** [comment]
I think you need to rebase

**Comment by BBasile** [comment]
No it's already done. I'm sure you had the same issue elsewhere (D-YAML / D-Scanner, i cant remember). There an event kind that has to be deactivated or something.

**Comment by wilzbach** [comment]
Ok I am currently on the road. Will have a look later.

**Comment by BBasile** [comment]
> I think you need to rebase

Yes it was that. appveyor config file was not yet present.

**Comment by BBasile** [comment]
Please someone, so that i can make the DCD pull request. This is actually a trivial change that has for effect to only handle two cases of initialization: if `true` or `false` is the init then a new hint is inserted in the breadcrumbs, saying that the target type is a `bool`...

**Pull request merged**
