### PR TITLE
Add Meson build definition

### PR DESCRIPTION
**Pull request by eclipseo**
Based on @ximion work on https://github.com/dlang-community/containers/commit/fc97b589e485d6e80e6f17c828abaa6c9fb27f35

### CODE REVIEW

**Comment by BBasile** [comment]
@eclipseo, CI failed in case you didn't notice yet.

**Comment by ximion** [comment]
Jup, wrap-files are missing (as Meson works without any central package registry) - it was likely just forgotten to commit them.

**Comment by bioinfornatics** [comment]
On fedora this patch works fine with ldc
https://koji.fedoraproject.org/koji/taskinfo?taskID=30148146

**Comment by BBasile** [comment]
The [LDC test doesn't pass](https://travis-ci.org/dlang-community/dsymbol/jobs/439239133#L618).

**Comment by BBasile** [comment]
The only difference with your build @bioinfornatics is then the travis config file. I've noticed that Meson 0.48 was used on Fedora Build but we can't use it because of a bug, which also means that you only build, otherwise you would have hit the Meson bug.

ps @eclipseo : sorry i've ruined your PR by editing online, you gotta pull and maybe squash my additions.

**Comment by eclipseo** [comment]
Rebased the thingie and squashed your commit.

**Comment by eclipseo** [comment]
Travis is failing because of https://github.com/dlang-community/containers/pull/118

**Comment by Hackerpilot** [comment]
Containers pull request was merged.

**Pull request merged**
