### PR TITLE
Make compatible with TypeIdentifierPart

### PR DESCRIPTION
**Pull request by BBasile**
Required after https://github.com/dlang-community/libdparse/pull/190

### CODE REVIEW

**Comment by BBasile** [comment]
Note that I also have to update the JSON, which by the way i'd like to convert to SDL.
The dependency attributes are really useful. For example i was able to do that to test everything with the local changes:

```yaml
dependency "libdparse" path="../libdparse"
```

and in dcd

```yaml
dependency "dsymbol" path="../dsymbol"
dependency "msgpack-d" version=">=1.0.0-beta.3 <1.1.0-0"
dependency "libdparse" path="../libdparse"
```

**Comment by BBasile** [comment]
We need to wait package.dlang.org to detect the release now 💤

**Comment by Hackerpilot** [comment]
```sdl
dependency "libdparse" path="../libdparse"
```
can also be written as
```json
"dependencies": {
    "libdparse": {"path": "../libdparse" }
}
```
That feature is not unique to the SDL package format.

**Comment by Hackerpilot** [comment]
Overriding the dumb Win64 CI.

**Pull request merged**
